### ISSUE TITLE
Failed to load target

### ISSUE THREAD

**Issue by AlastairCrowley** [fox-it/dissect#40]
Hi,
i recently started trying dissect but i get error messages all the time. My command was:

target-query /mnt/SCHARDT.001 -f hostname,domain,os,version,ips -d ';'
2023-12-12T13:19:53.452782Z [error    ] Unable to import dissect.target.plugins.filesystem.yara [dissect.target.plugin] 
2023-12-12T13:19:53.605162Z [error    ] /mnt/SCHARDT.001: Failed to load target with loader RawLoader('/mnt/SCHARDT.001') 

TargetError: Failed to load target: /mnt/SCHARDT.001

Traceback (most recent call last):
  File "/usr/local/bin/target-query", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/dissect/target/tools/utils.py", line 250, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/dissect/target/tools/query.py", line 243, in main
    for target in Target.open_all(args.targets, args.children):
  File "/usr/local/lib/python3.11/dist-packages/dissect/target/target.py", line 307, in open_all
    raise TargetError(f"Failed to find any loader for targets: {paths}")
dissect.target.exceptions.TargetError: Failed to find any loader for targets: ['/mnt/SCHARDT.001']

Do you have any ideas, what I'm doing wrong?
Thanks for your help.

p.s.: There is a longer and more detailed error output if you need it.

**Comment by AlastairCrowley** [comment]
Ok, that was the problem. Thank you.
Now i only have one more problem. Maybe you could help me with that one too.
I still get the error message:

[error    ] Unable to import dissect.target.plugins.filesystem.yara [dissect.target.plugin]

**Comment by AlastairCrowley** [comment]
Ok, thank you very much for your fast support.
